In [ ]:
#Power Iteration
import numpy as np
from scipy import linalg as la

def power_iteration(P):
    '''
    Input: Matrix P, number of iterations:n
    Output: dominant eigen vector of P
    '''
    no_nodes= P.shape[0]
    #initialize eigen vector
    r_new=np.random.rand(no_nodes)
    
    r_old=np.zeros(no_nodes)#vector to store old rank
    i=0 # number of iterations
    while (r_old!=r_new).all(): #stop when eigen vector converges
        r_old=r_new
        #r=P.r
        r_new = P.dot(r_old)
        
        # calculate the l1 norm
        r_norm= np.linalg.norm(r_new,ord=1)
        #nomalize r_new
        r_new=r_new/r_norm
        
        i=i+1
        if(i==1000):
            break
    #print("\nIterations:",i)
    return r_new
        
def page_rank_matrix(P):
    '''return the page rank matrix of P'''
    n=P.shape[0]
    G=0.85*P+0.15 *(np.ones((n,n))/n)
    return G


P=np.array([[0,0,1/2,1/3,1/2],[1,0,0,0,1/2],[0,1/2,0,1/3,0],[0,1/2,0,0,0],[0,0,1/2,1/3,0]])
no_nodes=P.shape[0]
r=power_iteration(P)
print("\nDominant eigen vector:\n-------------------------")
print(r)

#Page rank
#convert the matrix to Page Rank Matrix
print("\nGoogle page rank matrix\n----------------------")
G=page_rank_matrix(P)
print(G)
r=power_iteration(G)
print("\nRanking:-------------")
print(r)

#Page rank based on new rank
print("Page Rank based on new Ranking")
c=3
P=c*np.array([[0,0,1,1,1],[1,0,0,0,1],[0,1,0,1,0],[0,1,0,0,0],[0,0,1,1,0]])
print("Transition Matrix:----------------\n",P)

print("Google page rank matrix\n----------------------")
G=page_rank_matrix(P)
print(G)
r=power_iteration(G)
print("New ranking:\n-----------------")
print(r)



Dominant eigen vector:
-------------------------
[0.2195122  0.29268293 0.19512195 0.14634146 0.14634146]

Google page rank matrix
----------------------
[[0.03       0.03       0.455      0.31333333 0.455     ]
 [0.88       0.03       0.03       0.03       0.455     ]
 [0.03       0.455      0.03       0.31333333 0.03      ]
 [0.03       0.455      0.03       0.03       0.03      ]
 [0.03       0.03       0.455      0.31333333 0.03      ]]

Ranking:-------------
[0.22006221 0.28268547 0.19268137 0.15014133 0.15442962]
Page Rank based on new Ranking
Transition Matrix:----------------
 [[0 0 3 3 3]
 [3 0 0 0 3]
 [0 3 0 3 0]
 [0 3 0 0 0]
 [0 0 3 3 0]]
Google page rank matrix
----------------------
[[0.03 0.03 2.58 2.58 2.58]
 [2.58 0.03 0.03 0.03 2.58]
 [0.03 2.58 0.03 2.58 0.03]
 [0.03 2.58 0.03 0.03 0.03]
 [0.03 0.03 2.58 2.58 0.03]]
New ranking:
-----------------
[0.26573871 0.23536042 0.19551788 0.12859827 0.17478473]
